### ISSUE TITLE
Bit order incorrect.

### ISSUE THREAD

**Issue by ryman1** [bismurphy/Saleae_NEC_Decoder#1] opened 2024-03-13 08:07 UTC
The decoder does not take in to consideration that, with the NEC protocol, each individual byte is transmitted starting with the least significant bit (LSB) rather than the most significant bit (MSB). This causes the decoded bytes to be completely inverted, resulting in incorrect Base10 output from the decoder.

![image](https://github.com/bismurphy/Saleae_NEC_Decoder/assets/8972914/3fb5c877-a913-49b3-b6f2-d5a5224c4a41)
The left calculator has the IR code I was expecting to receive, and the right side has the data received from Saleae_NEC_Decoder

I find the diagram in the Protocol section of this page helpful for visualizing the layout:
![image](https://github.com/bismurphy/Saleae_NEC_Decoder/assets/8972914/b8edfaf0-1bc7-49ca-9400-ca6c5dbfe7b2)

Thanks for creating this. Even it's current state, it has helped quite a bit just with the start frame and repeat detections.

**Comment by bismurphy** [comment] 2024-03-13 15:12
Hi there! Thanks for opening an issue! I made this plugin 3 years ago and honestly had mostly forgotten about it; it's a nice feeling to know that people are making use of software I wrote.

That being said, let's see if we can work through your issue. If you look at the front page of this repository, you'll see an example capture in a screenshot. The bitstream shows a Start Frame, and then the first byte is a 2. And looking at the waveform, the 2-bit is in the proper location to indicate that it is correctly being parsed LSB-first.

If you are seeing a different-than-expected behavior, it would be extremely helpful to see a screenshot, showing the bytes that the decoder is identifying, along with your own explanation of decoding it by-hand and what results you expect. Then I can work out what's causing the disconnect and resolve it. Although it's been a while since I've touched this, I am very invested in making sure everyone gets the most out of the things I make and therefore I am very interested in making this work for you. Thanks!

**Comment by ryman1** [comment] 2024-03-14 21:06
Thanks for taking the time. After walking though the IR signal bit-by-bit as you suggested, I can confirm that your plugin is working correctly. This one was human error on my part. Sorry about that! 

The source of my confusion was that my two sources for my ground truth for the expected command codes (https://pasthev.github.io/sensus/ from a pronto code as well as the the learning function on my smart remote) both provided the identical hex code `20df 20dd`. But what I didn't expect was that these codes **were already LSB**. 

![image](https://github.com/bismurphy/Saleae_NEC_Decoder/assets/8972914/e0518d50-0471-4617-bfa5-c235f1381582)

So, I expected that `20df 20dd` (32, 223, 34, 221 in base 10) would be the output of your the plugin after NEC decoding. 
![image](https://github.com/bismurphy/Saleae_NEC_Decoder/assets/8972914/8414b35b-c1af-4c58-b235-88cf876d3e23)
Instead, I saw `04FB 44BB` (4, 251, 68, 187).

Looking closer at the first octet in my expected decode output: `0x20` vs the plugin output`0x04`:

expected output: 0010 0000
     plugin output: 0000 0100

The reversed bit orders then led me to open this issue. I should have looked closer to verify my claim!

**Comment by bismurphy** [comment] 2024-03-14 21:13
Glad to hear things are working as expected then! It sounds like in that case there's no issue, so I'll go ahead and close this, but feel free to circle back if you discover new issues, or have any ideas for improvements. Thanks for using the tool!

**Closed as completed by bismurphy** 2024-03-14 21:13 UTC
